### ISSUE TITLE
Please tag a release

### ISSUE THREAD

**Issue by darix** [free-audio/clap#107]
Packager would prefer to have a release for packaging so we can help enabling clap as part of distributions.

Thank you in advance.

**Comment by baconpaul** [comment]
Hi!

i see a collection of tags in this repo the latest being 1.0.2

I’m not an expert on the various flavors of packaging. Is there something missing in those tags?

rhanks!

**Comment by darix** [comment]
ah i was going by the "releases" box on the right side. which normally shows up even when you only have tags. But then dont mind. maybe doing the GH release process would be something for the future. omw to package it for opensuse.

**Comment by baconpaul** [comment]
Oh great!
