### ISSUE TITLE
Try searching your software in a search engine.

### ISSUE THREAD

**Issue by edge226** [free-audio/clap#121]
You're competing with an STD for the name... How has nobody noticed this?

I'd highly suggest deciding on a name that is not competing with an STD.

**Comment by Bremmers** [comment]
Google suggest nothing but CLAP plugin info if I search for CLAP plugin....

**Comment by edge226** [comment]
Ok. If you're cool when people searching "Clap" find 2 pages of Gonorrhea stuff before your software then seems good. I'm just letting you be aware that you're competing with an STD's search results. That was what happened with me anyways.
