### ISSUE TITLE
Race condition in the documented workflow for sending automation events from a plugin's UI

### ISSUE THREAD

**Issue by robbert-vdh** [free-audio/clap#124]
The example workflow for sending automation from a plugin's UI to the host mentions requesting a flush only if the plugin is not processing audio. This can result in a race condition if the host is currently calling `stop_processing()`. This should instead recommend always calling `request_flush()`, even if the plugin is currently processing audio. In that case the operation will simply be a no-op.

https://github.com/free-audio/clap/blob/55ee06f776669b94d63247a9c1dcb7dfa6056587/include/clap/ext/params.h#L54-L55

**Comment by abique** [comment]
Yes, this is true. I'll change it today.
