### ISSUE TITLE
Project doesn't install anything

### ISSUE THREAD

**Issue by yurivict** [free-audio/clap#134]

**Comment by baconpaul** [comment]
That’s correct. It is consumed by plugins which are the installable assets.

Are you thinking you would like a target that copies headers to /usr/include (or CMAKE_PREFIX/include) or what not? And also installs the static lib?

that’s not really the use pattern folks have with the code to date.

**Comment by yurivict** [comment]
Users distribute tarballs depending on clap.h without including clap.
For example: https://github.com/rncbc/qtractor/archive/refs/tags/qtractor_0_9_27.tar.gz

**Comment by baconpaul** [comment]
Ahh in the qtractor instance it seems clap is a submodule 

https://github.com/rncbc/qtractor/tree/master/src

And whatever process made the tarball, it seems, didn’t traverse the submodule contents.

**Comment by rncbc** [comment]
the github tarball is not the `official` release tarball anyway: please read https://qtractor.org

**Comment by baconpaul** [comment]
Ok cool so that solves the proximate issue

@robbert-vdh @abique you have more Linux etc packaging experience than I do but my instinct is for now we still want people picking their clap version and bundling it rather than doing an install/findpackage approach

**Comment by robbert-vdh** [comment]
@baconpaul Packagers would like to build all CLAP plugins in the repos against the same CLAP library version, but outside of that I don't see why CLAP would need an install target for the headers. But that won't solve the problem @yurivict ran into, which is that GitHub's automatic source tarballs (which is just `git-archive`) doesn't include submodules.

**Comment by abique** [comment]
I close, this is not a clap issue.
