### ISSUE TITLE
Incompatible with C++98

### ISSUE THREAD

**Issue by falkTX** [free-audio/clap#137]
Hi, the file in https://github.com/free-audio/clap/blob/main/include/clap/private/std.h includes `cstdint` in C++ mode, but this file is not properly available if building with `-std=c++98`.

**Comment by abique** [comment]
Hi,
Thank you for finding out.
Is that a problem? I guess it is just a matter of including `stdint.h` in that case.

**Comment by falkTX** [comment]
Yeah we need to use old `stdint.h` for C++98 builds (or older, not sure if that is a thing)
