### ISSUE TITLE
clap-plugin-template.clap file not built cross-platform

### ISSUE THREAD

**Issue by kmturley** [free-audio/clap#141]
According to your code, if tests are set to build, then the plugin template should also be built:
if (${CLAP_BUILD_TESTS}) {
  ...
  add_library(clap-plugin-template MODULE EXCLUDE_FROM_ALL src/plugin-template.c)
  ...
}
https://github.com/free-audio/clap/blob/main/CMakeLists.txt#L19

However when I run:
```
cmake -G "Ninja Multi-Config" -DCMAKE_EXPORT_COMPILE_COMMANDS=true -DCLAP_BUILD_TESTS=true -S ./sdk -B ./build
cmake --build ./build --config Release --target "clap-tests"
```

The `clap-plugin-template.clap` file is only generated in the Mac build:
<img width="947" alt="Screen Shot 2022-07-17 at 3 25 21 PM" src="https://user-images.githubusercontent.com/1710493/179427169-dc20e12e-9eec-4475-8b9d-57dbc507c881.png">
<img width="949" alt="Screen Shot 2022-07-17 at 3 25 46 PM" src="https://user-images.githubusercontent.com/1710493/179427171-81a9ea0c-a33e-4b9e-b8ac-2486cb3cb27b.png">
<img width="938" alt="Screen Shot 2022-07-17 at 3 25 57 PM" src="https://user-images.githubusercontent.com/1710493/179427173-4d2d32ff-6dce-4344-9f70-a333a00f5945.png">

Here is my GitHub pipeline with the commands/steps i'm running:
https://github.com/studiorack/studiorack-template-clap/runs/7380658263?check_suite_focus=true

Should a `clap-plugin-template.clap` file be generated for all three platforms?

**Comment by baconpaul** [comment]
I wonder if module is the wrong spec for win lin

**Comment by abique** [comment]
`MODULE` is correct:

> MODULE libraries are plugins that are not linked into other targets but may be loaded dynamically at runtime using dlopen-like functionality.

**Comment by kmturley** [comment]
Verified working on this job:
https://github.com/studiorack/studiorack-template-clap/actions/runs/3810171261/jobs/6482075291

Thanks for fixing!
