### ISSUE TITLE
"size" in `clap_input_events_t` is ambiguous

### ISSUE THREAD

**Issue by atsushieno** [free-audio/clap#158]
In `include/clap/events.h`, struct `clap_input_events_t` defines `size` function member.

https://github.com/free-audio/clap/blob/af1e05ce6487151c6b36003fdb47566dbb50194e/include/clap/events.h#L266

But what is "size" ? Length of event stream in bytes, or the total count of the messages? Typical other CLAP types say "count" when it returns a number of something, so maybe this is a bytes length? In either case, it should be clearly documented.

**Comment by baconpaul** [comment]
You are correct that "count" would be the consistent name; for clarity the API returns the number of events in the list not the number of bytes

**Comment by abique** [comment]
This struct abstracts a list/vector and in C++ people use `size()`.

**Comment by abique** [comment]
I've added documentation on the next branch.
