### ISSUE TITLE
Documentation for plugin API?

### ISSUE THREAD

**Issue by JBetz** [free-audio/clap#176]
Is there any documentation or specification of the plugin API for implementing hosts, or can it only be inferred from the example host? Also, where would be a good place to talk to other developers working on CLAP plugins and hosts?

**Comment by baconpaul** [comment]
Hi!

the header files in the source are extensively documented with the protocol and so forth. We’ve been focusing our efforts on keeping those accurate and expanding them as people go 

a few other things in addition to the example host

clap-info (also in the free audio GitHub project) is a command line tool which loads and prints information about a clap and is as such a starting point for the most basic host plugin interaction 

the clap saw demo (in the surge-synthesizer repo) is a heavily commented plugin which many people use as a first or second test plugin for a host 

finalky folks chat in discussions here but if you are working actively on clap there’s a few discords and stuff we use. The clap chatter channel on the surge discord is public and if you want to use discord find one of us there for more on chat venues

**Comment by JBetz** [comment]
Thanks! I'll post further questions in discussions.
