### ISSUE TITLE
clap.fd-support broken on WIN32

### ISSUE THREAD

**Issue by timkalu** [free-audio/clap#20]
the whole fd-support.h file does not compile, since read/write/close etc. don't work with ```void*``` types.

**Comment by abique** [comment]
I think on windows file handles are `HANDLE` or `HFILE` which is `void*` in the end.

https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-readfile
And I think `SOCKET` is a `HANDLE` in the end.

**Comment by timkalu** [comment]
a `SOCKET` is an `UINT_PTR`, a `FILE` is a `struct _iobuf`, `HFILE` is a `short` and a `HANDLE` is a `void *`.
unfortunately, those types do not match at all. What should fd finally be?

**Comment by abique** [comment]
According to the docs `OpenFile` returns a `HFILE` which should be closed using `CloseHandle` which itself takes a `HANDLE`.

https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-openfile
https://docs.microsoft.com/en-us/windows/win32/api/handleapi/nf-handleapi-closehandle
https://docs.microsoft.com/en-us/windows/win32/sysinfo/kernel-objects

Anyway, maybe this interface is not very useful on windows or even osx?
I think one can register events using win32 or cocoa's event loop on the main thread?

**Comment by abique** [comment]
I've addressed this issue by making this interface posix specific.
If windows needs something, then maybe it should be more windows specific.
