### ISSUE TITLE
Little UTF-8 issue in header files

### ISSUE THREAD

**Issue by Arakula** [free-audio/clap#232]
Some of the header files contain a UTF-8 BOM at the start. When using an old compiler (hey, it's basically ANSI C, so why not?), that can lead to problems; MS Visual C++ 6.0 (part of Visual Studio 98), for example, treats the byte order marks as syntax errors.

**Comment by abique** [comment]
How to fix it?

**Comment by Arakula** [comment]
Simply by removing the byte order mark from the start of the files

- clap.h
- ext/audio-ports.h
- ext/params.h
