### ISSUE TITLE
Include Universal MIDI Packets in Clap events

### ISSUE THREAD

**Issue by Engid** [free-audio/clap#24]
Hi there! This is an awesome project, thank you for working on it and making it available. 

I am wondering if we could please add a clap event type for the new Universal Midi Packets (UMP) defined in the Midi 2.0 spec that has recently been published. There should be examples for defining them in Apple's Core MIDI headers (MIDIMessages.h), and JUCE has a [template based implementation](https://github.com/juce-framework/JUCE/blob/master/modules/juce_audio_basics/midi/ump/juce_UMPacket.h) to account for the variable packet sizes. 

I would suggest defining structs for each packet size, which are comprised of `uint32_t` fields; ie, packets come in sizes of 32, 64, 96, and 128 bits. 

I'm no expert in the standard, but I am happy to help in any way to get MIDI 2.0 added to CLAP. 

Thank you,
-Nick

**Comment by abique** [comment]
Hi Nick,
The length of the packet can be determined by looking at the first 32 bits isn't it?
Regards,
Alex

**Comment by abique** [comment]
Yeah you can find about the size by looking at `mt` (message type).

**Comment by Engid** [comment]
Yes, thank you so much!
