### ISSUE TITLE
Versioning/tagging releases?

### ISSUE THREAD

**Issue by sadko4u** [free-audio/clap#258]
Hello!
I'm just about porting my plugins to support the CLAP format but I don't see any stable release, only set of commits to `master` branch.
It would be nice to have some versions of headers to reference to and, also, some macros in `<clap/clap.h>` to identify the versions of headers.

**Comment by robbert-vdh** [comment]
See [`clap/version.h`](https://github.com/free-audio/clap/blob/main/include/clap/version.h) (and PR #254 that made it easier to consume using C preprocessor directives, will land in CLAP 1.1.5 soon). Or if you're referring to git tags, this repo has those as well.

**Comment by sadko4u** [comment]
Nevermind, I didn't see the 'Releases' section on the right side and was confused by missing it. But I found tags and the version header, thanks. The issue can be closed now.
