### ISSUE TITLE
Is there any built-in program support?

### ISSUE THREAD

**Issue by AnClark** [free-audio/clap#271]
Hello!

Some plugin standards supports built-in programs. Users can directly choose a built-in program in host's preset picker. As far as I know, VST, VST3 and LV2 (via external TTL file) support it.

I wonder if CLAP supports this feature as well.

**Comment by robbert-vdh** [comment]
See #265 (now staged for the next CLAP version).

**Comment by abique** [comment]
Though, this is different to what a program is.
You can use MIDI Program Change for now.
