### ISSUE TITLE
Extend plugin features with expander and gate?

### ISSUE THREAD

**Issue by sadko4u** [free-audio/clap#274]
I don't see in `plugin-features.h` that plugin can feature `compressor` but can not feature `gate` nor `expander`.
Could be a good idea to add such features?

**Comment by sadko4u** [comment]
Also I find that `generator` feature is also missing.

**Comment by abique** [comment]
What is `generator` supposed to mean?

**Comment by robbert-vdh** [comment]
Presumably a test tone generator kind of plugin, so something that always generates colored noise or an always on sine wave oscillator.

**Comment by abique** [comment]
Please provide PR for generator with appropriate doc. The right approach may be to divide generator into multiple keywords.
