### ISSUE TITLE
GUI interface clarification

### ISSUE THREAD

**Issue by sadko4u** [free-audio/clap#278]
In the `struct clap_plugin_gui` we see the following interface function:

```C
   // Set the absolute GUI scaling factor, and override any OS info.
   // Should not be used if the windowing api relies upon logical pixels.
   //
   // If the plugin prefers to work out the scaling factor itself by querying the OS directly,
   // then ignore the call.
   //
   // Returns true if the scaling could be applied
   // Returns false if the call was ignored, or the scaling could not be applied.
   // [main-thread]
   bool(CLAP_ABI *set_scale)(const clap_plugin_t *plugin, double scale);

```

The main problem is, that there is no unit specification for the `scale` variable in the comment.
I assumed that it should be a multiplier which value `1.0` means that UI should be of the original, non-scaled size.
But the REAPER DAW reported `100` which, probably, means `100%`.
This should be clarified in the comment, what units are used.

**Comment by baconpaul** [comment]
Oooh good catch. I honestly don’t know which one was intended.

**Comment by abique** [comment]
1 for 100%.
