### ISSUE TITLE
[ext/preset-discovery] image provider should support embedded imaging

### ISSUE THREAD

**Issue by defiantnerd** [free-audio/clap#279]
regarding this:
https://github.com/free-audio/clap/blob/next/include/clap/factory/draft/preset-discovery.h#L198

Soundpacks often embed an image (or multiple images reg. resolution) within the file, so there is no file or URL for this.
Either this interface must be extended to allow resource streaming (including hinting for resolution) or it should be clarified, how a `data://` URI should look like to embed the image in the stream. 

I'd vote for the extended resource interface.

**Comment by abique** [comment]
I close the issue, for now.
Please re-open and elaborate on why a single HQ image isn't enough if I'm wrong.
