### ISSUE TITLE
[ext/preset-discovery] missing copyright/vendor string for collections

### ISSUE THREAD

**Issue by defiantnerd** [free-audio/clap#280]
`clap_preset_discovery_collection_t` should support a copyright string and/or a vendor string.
- the vendor might not be the same as the plugin vendor
- the copyright string might be an artist reference
-

**Comment by abique** [comment]
So if the collection needs more metadata, does it also need a creator or this is already implied by the presets?
Is the copyright a preset attribute or a collection attribute? Do you have examples what the copyright may look like? Do we need a set of constant strings for this?

Vendor -> OK.

**Comment by abique** [comment]
I think the copyright is more a preset attribute than a collection attribute.
