### ISSUE TITLE
gui: lots of functions lack what return value means.

### ISSUE THREAD

**Issue by atsushieno** [free-audio/clap#299]
Those functions in gui extension lacks documentation comment on what the return value means, for example in `clap_plugin_gui` :
  - `create()`
  - `get_size()`
  - `adjust_size()`
  - `set_size()`

It is not a comprehensive list. I think the entire specification should be reviewed and see if the overall documentation lacks description on parameters and return values, at least on non-draft ones.

**Comment by abique** [comment]
If those function return false, then it means they failed.

For example the GUI is on another computer, and your communication via the socket failed in `get_size()` so it returns false and the host should discard the with and height.

**Comment by niswegmann** [comment]
@abique, the function `suggest_title` in `clap/ext/gui.h` returns `void` and therefore shouldn't have the comment "Returns true on success.".
