### ISSUE TITLE
FR: add a "isPlayedLive" flag to the flags part of MIDI events

### ISSUE THREAD

**Issue by timkalu** [free-audio/clap#30]
FR: Add a "`isPlayedLive`" flag to the flags part of a MIDI event (notes etc.)

The reasoning behind this is:
A plugin that connects a hardware, a DSP processing card or has other reasons for higher latency can improve the user experience by ditching certain aspects like sample accuracy in exchange for a snappy feeling when played live.

To allow musicians to experience a snappy feeling, the original behavior of all notes that had a timestamp of 0 to be played as soon as possible it mentioned in the VST2 documentation. 
In VST2 the timestamp 0 of a note event was designated to be "play as fast as possible".

see Documentation of `struct vst_midi_event`:

> VstInt32 noteOffset
> 	offset (in sample frames) into note from note start if available, else 0
> 

Some of hosts didn't follow that rule so there is a change of 1/blocksize that this does not work correctly.

Therefore, VST2.4 introduced the `kVstMidiEventIsRealtime `flag.

from the documentation of `VstMidiEventFlags`:

> kVstMidiEventIsRealtime 
> 	means that this event is played life (not in playback from a sequencer track).
> 	This allows the Plug-In to handle these flagged events with higher priority, especially when the Plug-In has a big latency (AEffect::initialDelay)
> 

By the time of VST2, a timestamp of 0 was quite a good sign to distinguish notes in a playback from those played live. At least Cubase guaranteed this, but there was always the chance of 1/(buffersize) that it is actually a timestamped note, especially because other hosts may not give the guarantee.

For a host it is easy to decide when this flag is being set: as soon as a track is in „live mode“ and the events are coming from a „real“ MIDI input.

This flag is also implemented in VST3, see documentation of VST (VST/3/doc/vstinterfaces/ivstevents_8h_source.html):
```
struct Event
00101 {
00102    int32 busIndex;            
00103    int32 sampleOffset;        
00104    TQuarterNotes ppqPosition; 
00105    uint16 flags;           
00106    
00108    enum EventFlags
00109    {
00110       kIsLive = 1 << 0,       
00111       
00112       kUserReserved1 = 1 << 14,  
00113       kUserReserved2 = 1 << 15   
00114    };
```

and Audio Units (AU Property ```kMusicDeviceProperty_DualSchedulingMode```):
```
	@constant		kMusicDeviceProperty_DualSchedulingMode
	@discussion			Scope:				Global
						Value Type:			UInt32
						Access:				write
						Some instrument units need to distinguish realtime note and control events (such as from 
						incoming MIDI) from sequenced or pre-scheduled events. To support this, a host application 
						may set this property to 1. If the instrument unit returns a value of noErr, it supports 
						an alternate interpretation of the inOffsetSampleFrame parameter for the following 
						functions:
							MusicDeviceMIDIEvent
							MusicDeviceStartNote
							MusicDeviceStopNote
							AudioUnitSetParameter
						Once the host sets this property to 1 and the instrument unit returns noErr, the 
						inOffsetSampleFrame field becomes a bitfield:
							kMusicDeviceSampleFrameMask_SampleOffset = 0xFFFFFF // AND with this to obtain sample offset
							kMusicDeviceSampleFrameMask_IsScheduled = 0x01000000
						The IsScheduled bit should be set on events which are being scheduled ahead of time from 
						a prerecorded track. The IsScheduled bit should be clear on events which are being sent 
						to the instrument unit in response to realtime events, such as incoming MIDI or control 
						changes in a view.
```

**Comment by abique** [comment]
Fixed by https://github.com/free-audio/clap/blob/main/include/clap/events.h#L30
If it works for you then please close the issue :)

**Comment by timkalu** [comment]
👍
