### ISSUE TITLE
GUI extension - some methods are missing the floating/!floating tag

### ISSUE THREAD

**Issue by Trinitou** [free-audio/clap#313]
in `gui.h`:
Some methods don't have the floating / !floating tag although they are only for one of the modes, e.g
- can_resize
- adjust_size
- set_size
- request_resize?

Instead it is mentioned in the comment that the method is only for embedded windows. I think only the tags should be used instead of the comments.

**Comment by abique** [comment]
Maybe you want to make a PR for that?

**Comment by Trinitou** [comment]
> Maybe you want to make a PR for that?

If i find the time, I'll do. If somebody else is faster, no problem 😉

**Comment by Trinitou** [comment]
> Maybe you want to make a PR for that?

-> #315
