### ISSUE TITLE
32bit/64bit data choice questions

### ISSUE THREAD

**Issue by sburton84** [free-audio/clap#321]
Hi, I have some questions about the use of 32bit or 64bit processing in a plugin.

It seems like there's no way for the host to explicitly specify before processing which size it will be using, is that correct? There are flags for the plugin to indicate that it supports or prefers 64bit, but I can't see anything for the host to concretely specify which size it *will* be using? The only way to know whether the host is passing 32bit or 64bit data is to wait until processing starts then check which of the `data32` or `data64` pointers passed to the process function is `NULL` or not?

If so, this doesn't seem ideal; a plugin may need to allocate buffers of the appropriate size depending on whether 32bit or 64bit data is being used, and it's not ideal to have to allocate these in the audio processing function when they could easily be allocated beforehand if it was known which size to allocate. 

When the `activate` function is called it allows the host to specify the sample-rate it will be using. Would it not makes sense for the host to also specify the bit-depth at the same time?

**Comment by abique** [comment]
This is a good point.

We could extend the port activation extension so you know if the port is going to be used in 32 bits or 64 bits.
