### ISSUE TITLE
reverb tail length

### ISSUE THREAD

**Issue by Bremmers** [free-audio/clap#33]
AFAICS there's no way for a plugin to report reverb tail length like kAudioUnitProperty_TailTime (AU) / effGetTailSize (VST2) / IAudioProcessor.GetTailSamples (VST3). A host may use this to calculate the duration of a song.
Could be implemented similar to clap_plugin_latency.

**Comment by abique** [comment]
I think the tail length is used instead to know when to send an effect to sleep. In clap the process method already returns that info (continue to process or go to sleep).

I don't think the tail length can be used to know the length of a song for a simple reason: you can have delays feeding into a reverb and maybe even some feedback which would make it impossible or at least very complex to calculate the length of a song.

**Comment by abique** [comment]
I flag it invalid for now. Feel free to elaborate I'm open to discussion.

**Comment by Bremmers** [comment]
That's a very cool way to do it, but not all hosts are that radically modern ;-)

AFAIK the AU/VST tail property has always been supported by virtually all plugins that should. A host can use it to calculate the length of a mixdown or a track freeze beforehand. I don't know if many hosts actually use it.

I could probably get by without a tail property by applying some AI to clap_plugin_descriptor.keywords ;-)

**Comment by abique** [comment]
We may want it for providing compatibility with clap to vst2/au.

**Comment by reFX-Mike** [comment]
You definitely want as much feature-parity with VST2/VST3/AU/AAX as possible to attract any bigger plugin manufacturers. 

That's not going to say that every single feature offered from these four formats should be supported, but if a feature is supported by all four of them, then it's maybe a good idea to support it too. Kinda like a "lowest common denominator" of features. If all four have it, let's add it to CLAP.

**Comment by abique** [comment]
I think we'll provide it via an extension.

**Comment by abique** [comment]
Please let me know if the fix works for you.

**Comment by Bremmers** [comment]
clap_plugin_tail is perfect!

clap_host_tail and CLAP_PROCESS_TAIL are probably overkill. Other plugins formats don't have this either, IMO it would be better to remove them.

**Comment by abique** [comment]
If we don't have `clap_host_tail` then it means that the value is constant, or that the host should poll it periodically?
I think it is nice if this feature looks good even if it is not required for pure clap plugins and more of a support interface.

**Comment by reFX-Mike** [comment]
In other plugin formats, there is a call the plugin can make to let the host know that something significant changed. When the plugin calls that function, the host usually then re-evaluates the number of busses (input/output, number of channels for each bus, etc.) and also other pertinent information (tail-time, name of the current preset, etc.)

I think it would be a good idea to have something like that, but maybe something more lightweight, depending on what changed. If it's just the preset name, then that's lightweight. But if it's tail-time, or even the latency changing (thus affecting PDC) then that's a heavy call that might interrupt audio.

**Comment by robbert-vdh** [comment]
That's what those `clap_host_*` objects are for. Since CLAP is extensible, it makes more sense to have a dedicated notification function for everything significant about a plugin that may change during runtime, as opposed to having a single restart function with hardcoded restart flags.

**Comment by Bremmers** [comment]
The purpose of this extension is to allow a host to (easily) determine how much time the plugin adds to the source length. If the source is 3 minutes the only value that matters is the tail length at 3 minutes. There's no point in notifying the host of changes that occur after 1 minute because it's just the value at the end that matters.

The host can just ask for the value when all source material has been processed. Typically, though, it will ask for the value before (offline) processing starts.

Adding "solutions in need of a problem" needlessly complicates the API IMO.

**Comment by abique** [comment]
If the value is cache-able and not constant, then it needs an invalidation mechanism.

@Bremmers you're saying that there is no point in caching it, the host should just ask for it when it is done sending input to the plugin.

What if an automation is playing during the tail and changes the effective tail duration?

Also I can very well imagine that a host caches this value and assumes it is a constant like the latency, having a way to invalidate it makes it clear that it can change.

**Comment by Bremmers** [comment]
>  having a way to invalidate it makes it clear that it can change.
I can't argue with that :-)
