### ISSUE TITLE
Turn clap_audio_port_info bool fields into flags

### ISSUE THREAD

**Issue by Bremmers** [free-audio/clap#34]
Perhaps the is_main / is_cv / in_placebool fields of clap_audio_port_info should be turned into a single uint32 field with flags. This would make adding new flags in the future easier.
Shouldn't there be an is_SidechainInput ?

**Comment by abique** [comment]
This is a valid request :)
I have other plans for CV.

**Comment by abique** [comment]
Fixed in the next branch.
