### ISSUE TITLE
Question regarding parameter name vs module

### ISSUE THREAD

**Issue by sjoerdvankreel** [free-audio/clap#346]
Hi!

When i set up a clap_param_info_t for example like this:

.module = "oscillator 3"
.name = "octave"

From the comments in params.h: "The host should concatenate/format the module + name" i would expect this to show up in the host as "oscillator 3 octave". But, neither reaper nor bitwig seem to respect this. So i end up with 4 parameters named "octave", 1 for each oscillator. I double checked in the debugger attached to reaper that both .module and .name are correctly set. 

Is this 1) something that has still to be implemented by the hosts or 2) i misinterpreted the clap sdk or 3) i just messed up somehow? In case of (1) i will just prepend the module name myself with the risk of it later showing up as "osc 3 osc 3 octave" but thats not so bad. I could also ask bitwig but i understand they are very closely involved in developing clap, so, seems just as good to ask around here.

See screenshots below.

-thanks again, sjoerd

![parname_reaper](https://github.com/free-audio/clap/assets/2647549/c4496f7a-9843-4e87-93f5-f4dac65bcc6c)

![parname_bitwig](https://github.com/free-audio/clap/assets/2647549/024e2cf6-bc3b-4ca8-8e14-2bf065757396)

**Comment by defiantnerd** [comment]
Unfortunately, this is up to the host. In the vst3 wrapper the modules are being used to construct the units.

**Comment by sjoerdvankreel** [comment]
Thanks for the quick reply. I'll just do the concatenation manually and live with it if things ever show up like "osc 3 osc 3 param_name", i'm sure hosts will agree on this in the long term.
