### ISSUE TITLE
Is there anything like VST3's SampleAccurate::Parameter?

### ISSUE THREAD

**Issue by sjoerdvankreel** [free-audio/clap#347]
I understand the time-stamped event model already provides sample-accurate behaviour but i'm looking for something like this: https://steinbergmedia.github.io/vst3_doc/vstsdk/structSteinberg_1_1Vst_1_1SampleAccurate_1_1Parameter.html. 

That's basically just an easy way to go from a time-stamped automation event stream to a linear-interpolated audio-rate automation curve. Not too hard to do by hand but i'd rather not re-invent the wheel if there's something included in clap already.

-thanks again, sjoerd

**Comment by sjoerdvankreel** [comment]
Closing - it's not too hard to do manually.

**Comment by baconpaul** [comment]
oh sorry to miss the
the answer is "no there's nothing like that in clap helpers or clap"
