### ISSUE TITLE
Any host that implements CLAP_EXT_CONTEXT_MENU?

### ISSUE THREAD

**Issue by sjoerdvankreel** [free-audio/clap#348]
Both reaper and bitwig latest versions return null for host->get_extension(host, CLAP_EXT_CONTEXT_MENU). Should i go with this https://github.com/free-audio/clap-host as a dummy for the time being or am i better off to defer this untill there is better support? Or, am i completely overlooking something ?

-cheers, sjoerd

**Comment by baconpaul** [comment]
With bitwig 5.0.4 I get param context menus in surge working no problem.

**Comment by sjoerdvankreel** [comment]
My bad. I had both 4.4.6 and 5.0.4 installed and as it turns out i was looking at the old version all night. Quickly got rid of it ;)
