### ISSUE TITLE
Is it possible to receive raw midi events without advertising CLAP_NOTE_DIALECT_MIDI?

### ISSUE THREAD

**Issue by sjoerdvankreel** [free-audio/clap#349]
More specifically i'd like to go with CLAP_NOTE_DIALECT_CLAP only (so i dont have to deal with PCK later when adding polyphonic modulation) and still be able to receive raw midi cc messages so i can do pitchbend and channel volume etc. 

Judging from this https://forum.cockos.com/showthread.php?p=2681157 (and by playing around with reaper) at least in reaper CLAP_NOTE_DIALECT_MIDI enables/disables *all* midi messages, not just note messages. Is that how it's supposed to work? And if so, is there any harm in enabling CLAP_NOTE_DIALECT_MIDI but then just ignoring midi note on/off messages?

Thanks again for the great support.
-sjoerd

**Comment by baconpaul** [comment]
Some hosts don’t support clap notes so I think most folks just bite the bullet and support both. 

I ended up just doing full pckid matching with wildcards and it tuned out to be the most flexible choice

but to your direct question if you don’t support dialect midi then I theory you should get no midi messages, and if you don’t support dialect clap in theory you should not get clap note events, but bitwig breaks this last rule last I checked

**Comment by sjoerdvankreel** [comment]
Yeah i saw that, i'm mostly working from your clap-saw-demo and this https://www.kvraudio.com/forum/viewtopic.php?t=589258.   Anyway, best to play it safe then and actually support what i advertise as supported :)
