### ISSUE TITLE
Let CLAP_EVENT_NOTE_ON send MIDI 2.0 note attributes

### ISSUE THREAD

**Issue by Bremmers** [free-audio/clap#36]
The CLAP_EVENT_NOTE_ON event type should support sending the MIDI 2.0 note-on "attribute type" (8 bits) and "attribute data" (16 bits) fields.

The recently added comments in events.h say "plugins are encouraged to be able to handle note events encoded as raw midi or midi2". Either CLAP_EVENT_NOTE_ON must be able the send full MIDI 2.0 note-ons, or plugins must be forced to support raw midi2 note-ons.

**Comment by abique** [comment]
MIDI 2.0 notes can be sent using a MIDI 2 event.
What kind of attributes are those?

**Comment by Bremmers** [comment]
> What kind of attributes are those?

It can be used for anything. Some examples:
- fixed-point pitch
- the guitar string the note was played on
- the location where a drum pad was hit

**Comment by abique** [comment]
I understand.
We have extensible events now in clap and I think that those specialized events should be done via an extension.
