### ISSUE TITLE
Allow for sending higher resolution values for MIDI controllers

### ISSUE THREAD

**Issue by Bremmers** [free-audio/clap#37]
There should be a way to send higher resolution values for MIDI controllers. Could be done by changing clap_event_midi  to this:

typedef struct clap_event_midi {
   uint32_t port_index;
   uint8_t data[3];         //MIDI message with valid note velocity
   bool hiresvalueisvalid;  //if true: hiresvalue contains a higher resolution value that can be
                            //used instead of the 7 (or 14) bits value in data[]
   double hiresvalue;       [[-1..1] for pitchbend, [0..1] for controllers and channel/poly aftertouch
}

Alternatively MIDI 2.0 protocol messages could be used of course, but that would require the receiving end to support them.

EDIT: on second thought this should probably just be left to CLAP_EVENT_MIDI2...

**Comment by Bremmers** [comment]
A little background:

Currently CLAP provides floating point events for MIDI note velocities (CLAP_EVENT_NOTE_*) and MIDI poly aftertouch (CLAP_NOTE_EXPRESSION_PRESSURE). Pitchbends, controllers and channel aftertouch can only be sent using CLAP_EVENT_MIDI or CLAP_EVENT_MIDI2. Some developers will want to use CLAP_EVENT_MIDI2 because they have float or uint32/uint16 values and they don't want to trunc them to 7 bits for CLAP_EVENT_MIDI. The current plans inevitably lead to ALL host and plugins having to support CLAP_EVENT_NOTE_* AND CLAP_EVENT_MIDI AND CLAP_EVENT_MIDI2. All three of them!

I see two solutions:

1) use MIDI 2.0 channel voice messages only (and ditch everything else)
2) abstract away from MIDI a little bit and add event(s) to send Pitchbends, controllers and channel aftertouch as floats just like CLAP_EVENT_NOTE_*. In this scenario CLAP_EVENT_MIDI / CLAP_EVENT_MIDI2 are only required for things like Program Change.

I like 1) myself, but I guess most people would prefer 2). Either way, I strongly feel this needs to be improved.

**Comment by abique** [comment]
High resolution controllers can be sent using two consecutive midi messages.

The design is that you get **raw** midi and midi2 access.
