### ISSUE TITLE
events.h should explain CLAP_EVENT_NOTE_EXPRESSION vs. MIDI 2.0 per-note controllers

### ISSUE THREAD

**Issue by Bremmers** [free-audio/clap#40]
CLAP_EVENT_NOTE_EXPRESSION and MIDI 2.0 per-note controllers do exactly the same thing (with the possible exception of CLAP_NOTE_EXPRESSION_VOLUME and CLAP_NOTE_EXPRESSION_TUNING which work like their VST3 counterparts). What is a host supposed to use if it can choose?

FWIW: I appreciate some people don't like a raw MIDI API, but IMO it would be better to ditch CLAP_EVENT_NOTE_ON / CLAP_EVENT_NOTE_OFF / CLAP_EVENT_NOTE_EXPRESSION / CLAP_EVENT_MIDI in favor of CLAP_EVENT_MIDI2. Efforts to make it look easier just make it a bigger mess I'm afraid. There can be some utility conversion routines of course, there's just no need to burden the host/plugin interface specs with 3 ways to do the same thing if one way would do. It's asking for problems.

That said: CLAP makes a lot of sense and it's easy to implement so far :-), It's just the notes/MIDI1.0/MIDI2.0 thing that doesn't seem right.

**Comment by abique** [comment]
Thank you very much for all your feedback.
If the change does not address the issue, please re-open :)
