### ISSUE TITLE
Solve undefined UMP protocol issue

### ISSUE THREAD

**Issue by Bremmers** [free-audio/clap#41]
clap_event_midi2 contains UMP packets. UMP can use either the MIDI 1.0 or MIDI 2.0 protocol (see MIDI_2-0_Specification_Version_1-0/M2-104-UM_v1-0_UMP_and_MIDI_2-0_Protocol_Specification.pdf from midi.org). Currently there's no way to know what protocol the receiving end actually supports.

Proposal:
Add something like "Sending MIDI 1.0 protocol messages using CLAP_EVENT_MIDI2 is not allowed, use CLAP_EVENT_MIDI for MIDI 1.0 instead" to events.h.

**Comment by abique** [comment]
Does the dialect option solves your issue?
https://github.com/free-audio/clap/blob/next/include/clap/ext/note-ports.h

**Comment by Bremmers** [comment]
So CLAP_NOTE_DIALECT_MIDI2 would send MIDI 2.0 protocol messages using CLAP_EVENT_MIDI2?
And CLAP_NOTE_DIALECT_MIDI can use either CLAP_EVENT_MIDI or CLAP_EVENT_MIDI2 to send MIDI 1.0 protocol messages, depending on event-filter?

That would solve the issue indeed :-)

**Comment by abique** [comment]
If it is set to midi 1.0 I'd expect it to use CLAP_EVENT_MIDI. :)

So I can close that issue I suppose. Please re-open if you find another issue.

**Comment by Bremmers** [comment]
> If it is set to midi 1.0 I'd expect it to use CLAP_EVENT_MIDI. :)

Then you must document that.

You actually can send MID 1.0 using CLAP_EVENT_MIDI2 because UMP can contain MIDI 1.0 messages. In fact, Apple has deprecated CLAP_EVENT_MIDI-style MIDI 1.0 in favor of the CLAP_EVENT_MIDI2-style UMP messages. So some people will expect to be able to send MIDI 1.0 using UMP messages.

One could even argue CLAP_EVENT_MIDI should be removed because it will be old fashioned pretty soon...

See chapter 3.2 ("MIDI 1.0 Protocol in UMP Format") from M2-104-UM_v1-0_UMP_and_MIDI_2-0_Protocol_Specification.pdf
