### ISSUE TITLE
fix path to clap-helpers code in plugin-template.c

### ISSUE THREAD

**Issue by madronalabs** [free-audio/clap#411]
```
// plugin, I'd encourage you to use the C++ glue layer instead:
// https://github.com/free-audio/clap-helpers/blob/main/include/clap/helpers/plugin.hh
```

is apparently out of date, the correct path in the clap-helpers repo is

`include/clap/helpers/plugin.hh`

**Comment by baconpaul** [comment]
https://github.com/free-audio/clap-helpers/blob/main/include/clap/helpers/plugin.hh

I have no problem loading that URL? Am I mis-reading somehow? thanks!

**Comment by madronalabs** [comment]
That link works and I can't reproduce whatever lead to this comment—sorry for the noise.
