### ISSUE TITLE
Support for multiple languages in descriptors and parameter names

### ISSUE THREAD

**Issue by BillyDM** [free-audio/clap#42]
Is it possible to support an arbitrary amount of languages for things like the `clap_plugin_descriptor` and parameter names?

I think it would be best to use the language tag system as defined in RFC5646: https://datatracker.ietf.org/doc/html/rfc5646

Perhaps it could work something like this where each language version is separated by a `;`, similar to the list of keywords. Also if the user doesn't supply a `[<lang>]` tag, then the host assumes that only a single english version is given. (Please excuse any wrong words or grammar mistakes in this example, english is my only language).

```c
clap_plugin_descriptor_t my_plugin_descriptor {
   .clap_version = CLAP_VERSION;
   .id = "com.me.myplugin"
   .name = "[en]My Plugin;\
            [es]Mi Plugin;\
            [fr]Mon Plugin",
   .vendor = "[en]me;\
              [es]me;\
              [fr]me",
   .url = "[en]https://en.my-website.com;\
           [es]https://es.my-website.com;\
           [fr]https://fr.my-website.com",
   .manual_url = "[en]https://my-website.en-manual.pdf;\
                  [es]https://my-website.es-manual.pdf;\
                  [fr]https://my-website.fr-manual.pdf",
   .support_url = "[en]https://en.my-website.com/support;\
                   [es]https://es.my-website.com/support;\
                   [fr]https://fr.my-website.com/support",
   .version = "1.0.1",
   .description = "[en]goes beep-boop;\
                   [es]va beep-boop;\
                   [fr]va beep-boop",
   .keywords = "[en]synth;[en]beep;[en]boop;\
                [es]sintetizador;[es]beep;[es]boop;\
                [fr]synthétiseur;[fr]beep;[fr]boop;",
   .plugin_type = CLAP_PLUGIN_INSTRUMENT
};
```

Another way we could go about this is to change the `const clap_plugin_descriptor_t *desc;` field in the `clap_plugin` struct to a method that takes the language tag as a parameter. Then the user can decide if they want to return the given language or just return a default language if they don't support the given language:

```c
typedef struct clap_plugin {
   clap_plugin_descriptor_t (*desc)(const char* lang_tag, uint32_t lang_tag_size);
   
   ...
}
```

I also see that `clap_param_info` has a constant size for its name and module name buffer, so either that needs to be changed or we do the second thing again where we pass in the language tag as a parameter:

```c
// Copies the parameter's info to param_info and returns true on success.
// [main-thread]
bool (*get_info)(const clap_plugin_t *plugin,
                int32_t              param_index,
                clap_param_info_t   *param_info,
                const char* lang_tag,
                uint32_t lang_tag_size
);
```

It may also be necessary to either assert a specific text encoding standard like `UTF-8` or have a separate "text encoding type" field on the descriptor.

**Comment by baconpaul** [comment]
Encoding - if we can stick with utf8 everywhere life is so much easier.

My other thought here is: for daws which don’t support multi language we need to make things “easy”; your proposal requires a daw to parse language tags. I wonder if an internationalization extension is a better design inside the clap framework (Albeit English centric I understand.). An extension could allow the plugin to provide translations for everything etc…

**Comment by BillyDM** [comment]
Oh yeah, good idea! An extension does seem like a cleaner solution.

**Comment by timkalu** [comment]
I'd like to add that names and descriptors are often used as identifiers, too. In this case, a localization could lead to the situation where a song saved in a french UI would not load in a german one or categories wouldn't be recognized, depending on a host implementation.

**Comment by BillyDM** [comment]
> I'd like to add that names and descriptors are often used as identifiers, too. In this case, a localization could lead to the situation where a song saved in a french UI would not load in a german one or categories wouldn't be recognized, depending on a host implementation.

As for loading plugins in projects, I think the only thing that matters is the reverse-domain-name id of the plugin (i.e. "com.me.myplugin") which is separate from the localizations.

I guess there is a case to be made about tags and categories. I suppose we could leave those out of the localization stuff too and let the host translate them if it wants to.

But I still definitely want localizations for the name and description of the plugin, as well as the names of parameters and how the values of parameters are shown to the user. I know English has pretty much become the standard in the professional audio industry, but I would love to see a new plugin standard help break that trend and make the industry more inclusive, especially now when more and more people are producing music at home.

**Comment by abique** [comment]
The current locale is most of the time an OS setting.
I believe that the plugin can look at the OS setting and provide localized info.
If the OS do not provide localization settings, then I suppose that the question is irrelevant.
Note that even with bare metal embedded, there are likely something like `LC_LANG` environment variable.

**Comment by abique** [comment]
I close it as won't fix. Please re-open if you want to further discuss it.

I think that the host can just rescan the plugins if the OS locale change.
I recognize that re-scanning the plugins is not ideal, but I believe that it is the simplest solution, and locale change isn't a frequent thing.
