### ISSUE TITLE
Say something about UMP sysex data

### ISSUE THREAD

**Issue by Bremmers** [free-audio/clap#43]
For the sake of completeness:

1) The new UMP MIDI messages use 'normal' small messages for sending sysex data. This means CLAP_EVENT_MIDI2 can send sysex data. That's very inconvenient in a typical DAW/plugin scenario. I suggest adding a comment like this to events.h:

"While it's technically possible to send sysex data using CLAP_EVENT_MIDI2, hosts/plugins are not expected to support this. Use CLAP_EVENT_MIDI_SYSEX for sysex data."

2) UMP introduces a new 8 bits sysex data type (as opposed the the 7 bits sysex we all know). If this actually gains traction a CLAP_EVENT_MIDI_SYSEX8 message type could be added in the future. I think this can be ignored for now.

**Comment by abique** [comment]
Thank you.
1. is addressed in the branch next
2. then let's ignore it for now, and we'll do something for it once it is standardized and in use.
