### ISSUE TITLE
clap_event_param_value and clap_event_param_mod param_id/cookie aren't in the same order

### ISSUE THREAD

**Issue by Bremmers** [free-audio/clap#45]
The clap_event_param_value and clap_event_param_mod param_id/cookie aren't in the same order:

typedef struct clap_event_param_value {
   alignas(4) clap_event_header_t header;

   // target parameter
   void *cookie;                // @ref clap_param_info.cookie
   alignas(4) clap_id param_id; // @ref clap_param_info.id

typedef struct clap_event_param_mod {
   alignas(4) clap_event_header_t header;

   // target parameter
   alignas(4) clap_id param_id; // @ref clap_param_info.id
   void *cookie;                // @ref clap_param_info.cookie

clap_event_param_value should probably be changed to match clap_event_param_mod, that makes the struct a little smaller.

**Comment by abique** [comment]
Thank you, fixed in the branch next.
