### ISSUE TITLE
OSC support I/O

### ISSUE THREAD

**Issue by mkschulze** [free-audio/clap#47]
It would be nice to have OSC capabilities in the way that parameters could send their movements out as control data in OSC over the network and also may receive such messages.

This could serve as an inspiration maybe: https://plugins.iem.at/docs/osc/

**Comment by abique** [comment]
The plugin can do it itself right? It can open a socket a send data to it from another thread.

Or your asking for another note dialect?

**Comment by abique** [comment]
I close with wontfix, please re-open if you want to further discuss.
Anyway OSC is out of scope for the initial release.

**Comment by mkschulze** [comment]
Just wanted to mention this basically, in case there would need to be something essential that would be difficult to add at a later stage.

**Comment by abique** [comment]
Yeah, if there is something to be done in the future, I think we can still do it later. CLAP is very flexible today and we can add new "note dialects", via extensions.
