### ISSUE TITLE
clap_vst3_converter.convert_state can't handle editor state

### ISSUE THREAD

**Issue by Bremmers** [free-audio/clap#54]
I'm mentioning this just to make sure it's not an oversight. If you think it's not a problem then it's fine with me.

VST3 plugins have two states: one for the processor and one for the editor (ui). clap_vst3_converter.convert_state accepts the processor state only. That probably isn't a problem for most - if not all - plugins as there's nothing important in their editor state.

A second clap_istream_t parameter could be added for the editor state, to make sure no plugins are left out in the cold.

**Comment by abique** [comment]
Hi @Bremmers,
Thank you for the report this is indeed an oversight!
