### ISSUE TITLE
Minor style improvement for clap_note_port_info

### ISSUE THREAD

**Issue by Bremmers** [free-audio/clap#55]
Just a style issue: the clap_supported_dialects / clap_preferred_dialect fields of clap_note_port_info should probably be renamed to supported_dialects / preferred_dialect.

**Comment by abique** [comment]
Good catch again, you're doing an amazing job! :+1:

**Comment by Bremmers** [comment]
You're welcome.
Lots of improvements today!  👍

**Comment by abique** [comment]
Yes!
I'll try to merge next into main this week.
I'm still giving some thought to your UMP request.

**Comment by Bremmers** [comment]
Great, I'll try the changes once they're in main.

FYI: I've implemented almost all hosting code, and it all fits together very nicely! The only things that are causing me a bit of a problem are rescanning audio ports and rescanning params. My code doesn't expect these things to change at all, so I'll need to do some work on that.

**Comment by abique** [comment]
Which product are you working on? I could add a link to it in the clap readme?

**Comment by Bremmers** [comment]
MultitrackStudio (www.multitrackstudio.com)

**Comment by abique** [comment]
Amazing! :-)
Let me know if you want me to link your host in the readme :+1:
