### ISSUE TITLE
Improvement for audio ports extension

### ISSUE THREAD

**Issue by BillyDM** [free-audio/clap#57]
Currently the audio ports extension spec defines all settings per-port in this struct:
```c
typedef struct clap_audio_port_info {
   alignas(4) clap_id id;                // stable identifier
   alignas(1) char name[CLAP_NAME_SIZE]; // displayable name

   alignas(4) uint32_t channel_count;
   alignas(4) clap_chmap channel_map;
   alignas(4) uint32_t sample_size; // 32 for float and 64 for double

   alignas(1) bool is_main;  // there can only be 1 main input and output
   alignas(1) bool is_cv;    // control voltage
   alignas(1) bool in_place; // if true the daw can use the same buffer for input
                             // and output, only for main input to main output
} clap_audio_port_info_t;
```

First off, I don't think that `in_place` makes sense to specify per-port.

Second, I think allowing the user to set any port index as the "main" port adds unnecessary complexity on the plugin and the host. The main ports should just always be the first port in the list.

Third, I don't think we should allow plugins to have a mix of float and double buffers. This just adds a whole bunch of unnecessary complexity for both the plugin and the host. If it was intended to not mix buffer types, then this should be more clear in the spec.

As such, I think a better solution would look like this:
```c
typedef struct clap_audio_port_info {
    alignas(4) clap_id id;                // stable identifier
    alignas(1) char name[CLAP_NAME_SIZE]; // displayable name
 
    alignas(4) uint32_t channel_count;
    alignas(4) clap_chmap channel_map;
 
    alignas(1) bool is_cv;    // control voltage
 } clap_audio_port_info_t;

 enum {
    // Neither the first input port nor the first output port are "main" ports
    CLAP_MAIN_PORT_CONFIG_NONE = 0,
 
    // The first input port is a "main" port, but the first output port
    // is not a "main" port
    CLAP_MAIN_PORT_CONFIG_INPUT_ONLY = 1,
 
    // The first output port is a "main" port, but the first input port
    // is not a "main" port
    CLAP_MAIN_PORT_CONFIG_OUTPUT_ONLY = 2,
 
    // Both the first input port and the first output port are "main" ports,
    // but the host may not use the same buffer for both ports
    CLAP_MAIN_PORT_CONFIG_BOTH = 3,
 
    // Both the first input port and the first output port are "main" ports,
    // and the host may use the same buffer for both ports
    CLAP_MAIN_PORT_CONFIG_BOTH_IN_PLACE = 4,
 };
 typedef int32_t clap_main_port_config;
 
 // The audio ports scan has to be done while the plugin is deactivated.
 typedef struct clap_plugin_audio_ports {
    // number of ports, for either input or output
    // [main-thread]
    uint32_t (*count)(const clap_plugin_t *plugin, bool is_input);
 
    // get info about about an audio port.
    // [main-thread]
    bool (*get)(const clap_plugin_t    *plugin,
                uint32_t                index,
                bool                    is_input,
                clap_audio_port_info_t *info);
    
    // get the main ports configuration
    // [main-thread]
    clap_main_port_config (*main_ports)(const clap_plugin_t *plugin);

    // the sample size of all ports (32 for float and 64 for double)
    // [main-thread]
    uint32_t (*sample_size)(const clap_plugin_t *plugin);
 } clap_plugin_audio_ports_t;
```

**Comment by Bremmers** [comment]
I agree the main port should always be the first port in the list. What problem does this feature solve?

BTW: the audio ports have been reworked in the 'next' branch already.

**Comment by abique** [comment]
Thank you for taking the time to write this proposition.

Currently there is no requirement for having a "main" port in the plugin.

One example would be a plugin which models a component that takes a few CV audio input, and has a few CV audio output. None of them would be a main audio input / output. I think it is a valid example right?

If we say that the first port is implicitly the main input/output, then it would be impossible to realize the example above, which has no main input and output.

`in_place` has already been reworked in the next branch.

Mixed double/float. I disagree there are situations where double makes an absolute difference; it depends on the type of data, and how it is used. You may want all your ports to be float, and for one port that takes a CV signal which is then accumulated, having this port in double precision make sense.

Is the complexity you're thinking about a C++ template complexity where instead of having one sample_type, you'd have one for every audio ports?

**Comment by BillyDM** [comment]
> If we say that the first port is implicitly the main input/output, then it would be impossible to realize the example above, which has no main input and output.

That's what my proposed `CLAP_MAIN_PORT_CONFIG_NONE` enum variant is for.

I'm trying to write an audio graph engine for my DAW, and allowing any port to be the "main" port increases complexity for no reason. Either the plugin should use the first port as its main port, or it should specify that it has no main ports at all.

> Is the complexity you're thinking about a C++ template complexity where instead of having one sample_type, you'd have one for every audio ports?

The complexity comes from trying to write my audio graph engine. Allowing plugins to have a mixture of both increases the complexity of this engine, and also requires me to send two arrays of port buffers (one for f32 and one for f64) instead of only needing to send one array for either f32 or f64. Although that CV signal use case is a good point.

**Comment by Bremmers** [comment]
Perhaps CLAP_AUDIO_PORT_IS_MAIN can be removed, and the rule becomes that the first 'normal' audio input (ie. the first one that's not a CLAP_PORT_CV) is the main input.

This also makes AU/VST2 converters easier. Here the de-facto standard is that the first input is the main input, and the second input is the sidechain input.

CLAP_AUDIO_PORT_IS_MAIN allows for plugins to swap the main and sidechain input, which needlessly complicates things. And there'll be plugin that forget to flag an input CLAP_AUDIO_PORT_IS_MAIN, in which case the host still has to find the first suitable input.

**Comment by baconpaul** [comment]
Surge is a synth with a sidechain and no main input and setting that up is key for correct routing in several cases. Although I agree advertising no main is fine, no main is a real and important use case!

**Comment by BillyDM** [comment]
Yes, but my proposal is that either the main port is the first port in the list or there is no main port at all. Having the main port be a any index other than the first port just needlessly complicates things for the host.

**Comment by baconpaul** [comment]
Yup I have no problem with that. The fact that main can be a different bus in vst3 always seemed odd to me

**Comment by abique** [comment]
I agree with the request.
