### ISSUE TITLE
clap_audio_buffer::constant_mask - do buffers need to be filled properly?

### ISSUE THREAD

**Issue by signaldust** [free-audio/clap#58]
The bitmask specifies that a buffer is constant (thank you), but at least the header doesn't currently specify whether or not the whole buffer still needs to be actually filled with the constant value. I feel like this should probably be stated explicitly (whatever the intended meaning), because there are pros and cons with regards to any particular choice of specification.

If the whole buffer must always be filled, then any implementation can safely ignore the mask. If I had to guess, I'd assume this is the intention, but I'd be nice to have it clarified explicitly.

On the other hand, if implementations must respect the flag (eg. only the first element of the buffer needs to be set to the valid value), then there are some minor memory bandwidth savings to be had (for any buffer spanning more than one cache line), by not having to explicitly do a clear, although I suppose then one should specify that the buffer memory must still be valid and the recipient of the buffer must be allowed to lazy-clear (eg. in a wrapper that can't deal with such constant buffers natively).

**Comment by abique** [comment]
Hi,

Thank you for your question and it is worth clarifying.

It'd be nice to require the plugin/host to carefully check the constant mask, but illusory to believe that they will actually do it.
And if the rest of the buffer is filled with garbage then, it may result in garbage being routed to the speaker with all the bad consequences it can have.

So the buffer should be filled with the constant value. It is the safe choice.

How to optimize it:
- you need a singleton buffer filled with 0 to handle silence
- for CV/GATE signals, the constant value may remain the same from one block to the next, so if you see that the buffer was constant in the previous block and the constant value is the same, then you don't need to change it.

**Comment by abique** [comment]
Feel free to re-open and continue the discussion if needed :-)

**Comment by signaldust** [comment]
All good, I just figured a clarification would be in place.
