### ISSUE TITLE
Rearrange the CV draft extension's values enum

### ISSUE THREAD

**Issue by robbert-vdh** [free-audio/clap#59]
Super minor nitpick, but if this design ends up being used, then I'd propose the generic `CLAP_CV_VALUE` to be the first value in the list. Otherwise if you end up adding more useful standardized CV types in the future, it would end up somewhere in the middle of the list.

https://github.com/free-audio/clap/blob/75dabe9c6c53192dc6249134c8bb9e562fa915a0/include/clap/ext/draft/cv.h#L17-L22

**Comment by abique** [comment]
Good catch.
And `VALUE` is a good default after `memset(0)`.
