### ISSUE TITLE
raw midi in clap?

### ISSUE THREAD

**Issue by steveschow** [free-audio/clap#61]
This is a question, maybe a suggestion....  I have not tried to make a CLAP plugin yet, so please forgive any ignorance.

I notice there is something in CLAP called a "note port".  I am a little concerned that CLAP may be separating the raw midi stream into seperate queues between notes and other types of midi events.  Midi is fundamentally a serial protocol, such that even when there are midi events with the same timestamp, they are typically processed in the order they appear in the queue.  With VST2, all midi events were in one queue, so we could rely on that order being respected.  With VST3, the notes are separated from other midi events, the plugin sees parameters in seperate place from the notes..and basically any ordering within a single timestamp across different midi events is lost in VST3.

This can be a problem in certain keyswitching scenarios, for example...if you have a chord, with all notes on the same time stamp...and you have CC instrument  switches being used, with different CC switch per note of the chord....it will be broken in VST3 compared to VST2...because the the last CC of that timestamp will be applied to affect all the notes of the chord.  

In the future we have Midi 2.0 which is part of why Steinberg abstracted non-note midi events, I get that, but we need to make sure that the exact ordering of midi events as present in the raw midi stream is still maintained, even for events on the same timestamp...that has been a fact with midi for decades that the serial order of the events could be trusted...and it particularly comes up with keyswitching, when using expression maps, etc.. its common for CC switches and key switches to be on the same timestamp as the notes they are affecting..and when there are multiple notes in a chord on that timestamp...well...therein lies the problem.

Hope the CLAP team will not miss this point..  Steinberg did miss it with VST3 and I consider it a design flaw in VST3

**Comment by abique** [comment]
With clap you can have many events on a single port at the same time.
Adding another note port is like adding another midi input/output on a physical device.

Also with clap there is a single event queue. So everything is serialized.
