### ISSUE TITLE
A size method for clap_istream (reading plugin state)

### ISSUE THREAD

**Issue by robbert-vdh** [free-audio/clap#62]
Right now the `clap_ibstream` that's used for restoring plugin state does not have a way to query how much data there is left. Every other plugin API provides some way to know how large a state so you can have the option to read everything in one go instead of having to read it chunk by chunk. And reading the state in chunks works, but for the sake of staying in line with the expected behavior I think it would make sense to have have a size method on the `clap_istream` object that always returns the exact remaining length of the stream. The host would always need to know how much data there is left anyways, since otherwise it would not know when to stop reading memory. Or it can store the length in a header, like what's done in most binary file formats. This simply moves some of the responsibility of reading keeping track of the size for unbuffered reads from the plugin to the host.

If at some point an extension requires streams that do not have a known length (I can't name a sensible example, but I guess an `istream` could be used for generating random numbers?), then I feel like it would make the intent even clearer to have a `clap_istream_unsized`/`clap_istream_infinite` or something like that to indicate that the stream does not have an end.

**Comment by abique** [comment]
I guess we can close this one now, as it is release like this.
