### ISSUE TITLE
Out of date documentation in params.h

### ISSUE THREAD

**Issue by AlexHarker** [free-audio/clap#66]
From params.h

```
/// - set the flag CLAP_EVENT_BEGIN_ADJUST to mark the begining of automation recording
/// - set the flag CLAP_EVENT_END_ADJUST to mark the end of automation recording
/// - set the flag CLAP_EVENT_SHOULD_RECORD if the event should be recorded
```

These macros don't exist anymore. I presume we are to use three events:

```
/// - CLAP_EVENT_PARAM_GESTURE_BEGIN;
/// -  CLAP_EVENT_PARAM_VALUE;
/// -  CLAP_EVENT_PARAM_GESTURE_END;
```

all with values attached - is that correct?

Whether or not that's correct the docs need updating in params.h

Thanks

**Comment by baconpaul** [comment]
It is correct to use those three events; the API changed between 0.21 (where they were flags) and 0.23 (where they became events). (I agree param.h needs an update to clarify this but just thought this fact may be useful if you re developing now).

**Comment by AlexHarker** [comment]
Thanks - I've already made the changes as above and it works correctly as far as I can see, but I wanted to double check!

**Comment by abique** [comment]
Thanks for the catch! :)
