### ISSUE TITLE
Question about the necessity of 64 bit buffers

### ISSUE THREAD

**Issue by BillyDM** [free-audio/clap#68]
Not that I really expect you to remove 64 bit buffers from the spec, I just wanted to give my two cents and maybe spark some discussion on this.

There is little to no benefit in quality when it comes to using 64 bit buffers in the host's audio graph. Only a few special-case DSP algorithms really need 64-bit buffers, and it is usually better to just have the plugin convert the buffers internally if it actually needs it.

Supporting 64 bit buffers on the host side also adds a whole lot of complexity to the host's audio graph. Unless you know that all the plugins in your audio graph support 64 bit then it's not really worth it IMO.

I understand that if you did remove 64 bit buffers from the spec users will probably just demand it be added back. I'm just giving my two cents on it and maybe spark discussion if it is really necessary in the grand scheme of things. Perhaps 64 bit buffers could be an extension instead?

(Oh, I also just realized that I posted this on April 1st. This is a real post and not a joke.)

**Comment by robbert-vdh** [comment]
IMO 64-bit audio on the graph level indeed exists only to be able to add it as a selling point to the DAW's spec sheet. Plugins can and should use 64-bit floating point numbers internally if they can benefit from it, but for summing and scaling channels (which are the only operations on the audio graph level) it doesn't have any added value.

**Comment by abique** [comment]
The host has no requirement to do in-place processing.
The plugin has no requirement to do in-place processing either, if it does not support just set the pair id to `CLAP_INVALID_ID`.

**Comment by BillyDM** [comment]
> The host has no requirement to do in-place processing.
> The plugin has no requirement to do in-place processing either, if it does not support just set the pair id to `CLAP_INVALID_ID`.

Did you mean to post this in the other issue I made #69?

**Comment by abique** [comment]
> > The host has no requirement to do in-place processing.
> > The plugin has no requirement to do in-place processing either, if it does not support just set the pair id to `CLAP_INVALID_ID`.
> 
> Did you mean to post this in the other issue I made #69?

Ah yes!
