### ISSUE TITLE
Question about the necessity of in-place buffers

### ISSUE THREAD

**Issue by BillyDM** [free-audio/clap#69]
This is not so much a question on whether in-place buffers should stay in the spec, but rather if it is worth it to support it in my host/audio-graph system.

I have heard from other developers that there is no real-world performance benefit to using in-place buffers, and even if there was the performance gains are minimal at best. Can anyone more experienced with hosting plugins and audio graphs verify if this assumption is true or not? I've also heard that Bitwig doesn't use in-place buffers, so if it's good enough for them then it's good enough for me. Is it true Bitwig doesn't use in-place buffers?

I understand that using in-place buffers can make it easier to develop simple hosts, and this is may be the main reason for including this feature in the spec in the first place. However, in my host/audio-graph system the opposite is true. Our [audio graph compiling algorithm] works better when buffers are not in-place.

In-place buffers also pose a challenge for Rust, since Rust does not allow aliasing pointers to mutable data. Creating a safe, clean, and performant abstraction over this has proved to be a challenge. It would be great if we could just ignore in-place buffers in our Rust ecosystem, but I want to make sure that we aren't leaving any real-world performance gains on the table.

(Note, I am posting this on April 1st, but this is a real post and not a joke.)

[audio graph compiling algorithm]: https://github.com/MeadowlarkDAW/audio-graph

**Comment by BillyDM** [comment]
From #68:

> The host has no requirement to do in-place processing. The plugin has no requirement to do in-place processing either, if it does not support just set the pair id to `CLAP_INVALID_ID`.

Yes, I know that in-place processing is currently optional on both the host and plugin side. I'm asking if anyone here knows if in-place processing actually has any meaningful real-world performance gains.

**Comment by abique** [comment]
> From #68:
> Yes, I know that in-place processing is currently optional on both the host and plugin side. I'm asking if anyone here knows if in-place processing actually has any meaningful real-world performance gains.

Let's say you have N plugins, which have a single input and output, they're all in serial and all supports in place processing, I suppose that yes it can be interesting, especially if you are limited on memory and if your processor have a small cache. I haven't bench-marked it though. Some people claims that it is important to them.

**Comment by BillyDM** [comment]
> especially if you are limited on memory and if your processor have a small cache

I imagine most modern systems (as in the last decade) have far more memory and cache than what they had back when `process_replacing()` was introduced in the VST2 spec. Especially since I plan on running my audio graph with relatively small block sizes (64 - 1024 frames) with 32 bit buffers only, I have a suspicion the cache in modern CPU's makes in-place processing irrelevant in most real-world cases.

**Comment by abique** [comment]
I can't say, you should benchmark it.
It has benefit if you have a low memory system and if the cache miss cost is high.
It seems to matter to some people.
I think it'd be the last thing that I'd optimize on a modern system.
