### ISSUE TITLE
Meaning of CLAP_AUDIO_PORTS_PREFERS_64BITS

### ISSUE THREAD

**Issue by glowcoil** [free-audio/clap#70]
The meaning of the `CLAP_AUDIO_PORTS_PREFERS_64BITS` flag seemed a bit vague to me and I wanted to clarify.

If the `CLAP_AUDIO_PORTS_PREFERS_64BITS` flag is true for an audio port, does that mean the host must provide a 64-bit buffer, or that the plugin will support either 32- or 64-bit and simply prefers 64-bit? Likewise, if the `CLAP_AUDIO_PORTS_PREFERS_64BITS` flag is false for an audio port, does that mean the host must provide a 32-bit buffer, or that the plugin will support either and simply prefers 32-bit?

The comment at the top of `audio-ports.h` specifies that if a plugin does not implement the audio ports extension, it only supports 32-bit audio, which makes sense. But if a plugin does implement the extension, can it still specify that it only supports 32-bit audio by setting `CLAP_AUDIO_PORTS_PREFERS_64BITS` to false on all its ports? Or does implementing the audio ports extension mean that the plugin must unavoidably support both 32- and 64-bit audio, and can only specify a "preference"?

**Comment by robbert-vdh** [comment]
I asked the same thing in https://github.com/free-audio/clap/pull/71#discussion_r841730054, so I'll repeat the comment here for visilibity:

> In which situation would this preference [referring to `CLAP_AUDIO_PORTS_PREFERS_64BITS`] be useful? Wouldn't hosts either use 32-bit audio internally and pass that audio to plugins as is, or use 64-bit audio in their audio graph and either convert it to and from 32-bit for plugins that don't support 64-bit audio or pass that to plugins as is? The host converting its own 32-bit audio to 64-bit for a plugin wouldn't be very useful, in that case the plugin could just do the conversion themselves (and save on a buffer memcpy).

**Comment by abique** [comment]
It is required to support 32 bits, always.
supports means that 64 can be used.
preferred means that ideally the host should use a 64 bit audio buffer but this is not a requirement.

**Comment by baconpaul** [comment]
There isn't a supports_64 flag though is there?

So all ports must support 32 bit fine
but they can also support or support-and-prefer 64
the former means daw option, use float if you can
the second means daw option, use double if you can
and there is no version for must-use-double because not all daws support it?

but if that's the case aren't we missing a flag?

**Comment by glowcoil** [comment]
It looks like the 0.2.4 pull request (#71) adds a `CLAP_AUDIO_PORT_SUPPORTS_64BITS` flag, which addresses that problem and pretty much resolves my original question.

**Comment by baconpaul** [comment]
oh sorry duh i was reading 0.23 code when i typed this. apologies. ignore me.
