### ISSUE TITLE
Question about clap_host.request_process()

### ISSUE THREAD

**Issue by BillyDM** [free-audio/clap#83]
After the host calls `clap_plugin.activate()`, does it have to wait to receive a `clap_host.request_process()` request from the plugin before it can start processing?

**Comment by BillyDM** [comment]
> No, `clap_host.request_process()` is for explicitly requesting the host to start processing audio on the plugin if the plugin currently idle. This could be useful for instance when an interaction with the plugin's GUI should cause sound to be played even when the plugin is currently deactivated because it didn't have anything else to up until that point.

I see, thanks!

**Comment by abique** [comment]
@robbert-vdh answered correctly, thank you :-)
I will then closed the issue.
